In [1]:
# Importing packages

import numpy as np # Numpy is doing linear algebra and all the math for us
import random # Random to create random numbers

# Information on autoreload which will be important to update your modules 
# when you change them so that they work in the jupyter notebook
# https://ipython.org/ipython-doc/3/config/extensions/autoreload.html
%load_ext autoreload
%autoreload 2
#%reload_ext autoreload

In [2]:
#import rawpy
import numpy as np
import glob
import cv2
from PIL import Image
import os
import matplotlib.pyplot as plt
from matplotlib.pyplot import imshow

In [8]:
import src.code as code


In [22]:
code.sum_numbers(1,2)


3

In [24]:
code.multiply_numbers(2,3)


6

In [28]:
code.create_add_matrix(3)

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [34]:
code.indexing_aggregation([1,2,4,4,5], 3)


2.3333333333333335

In [36]:
A = np.array([[4,7],[2,6]])


In [38]:
A_inv = code.matrix_inverse(A)
print(A_inv)

[[ 0.6 -0.7]
 [-0.2  0.4]]


In [39]:
# Verify that this is the actual inverse
np.matmul(A,A_inv)
# The should be a matrix with only ones on the diagonal

array([[ 1.00000000e+00, -1.11022302e-16],
       [ 1.11022302e-16,  1.00000000e+00]])